### ISSUE TITLE
Any issues with youtube-dl?

### ISSUE THREAD

**Issue by escorciav** [gurkirt/kinetics-download-prep#1]
Hi Gurkirt,

Thanks for putting this together.

Have you noticed any recent issues with `youtbe-dl`?
[someone](https://github.com/activitynet/ActivityNet/issues/28#issuecomment-521727683) reported that Youtube is blocking the mass downloading of videos.

Cheers,
Víctor

**Comment by gurkirt** [comment]
Hi Escorciav,

I don't think so, I had about 516K videos from the past and I was able to download additional 315K videos. 

Another issue I got was the version of FFmpeg, I think default version of FFmpeg is 4.0 but that doesn't work in our case, using FFmpeg 3.1.3 from menpo works.

Cheers
Gurkirt

**Comment by gurkirt** [comment]
Also, my environment is different than [yours](https://github.com/activitynet/ActivityNet/blob/master/Crawler/Kinetics/environment.yml). Because that didn't work with the latest anaconda 3.7.

**Comment by escorciav** [comment]
Thanks. I see so there are many differences.

What about the version of `youtbe-dl`?

**Comment by gurkirt** [comment]
I think the latest. 
`youtube-dl --version` prints out `2019.08.13`
I used `pip install --upgrade youtube-dl` to install it.
