### ISSUE TITLE
Suggested Dataset class for pytorch?

### ISSUE THREAD

**Issue by 2198310932i1** [gurkirt/kinetics-download-prep#4]
Thanks for putting the time in modifying the original crawler to take up less space. Is there a suggested Dataset class / loader for pytorch you could recommend? I'd rather avoid rolling one from scratch if that's possible. 

Looking forward to hearing back from you!

**Comment by gurkirt** [comment]
I modified the ones from https://github.com/facebookresearch/SlowFast/tree/master/slowfast

**Comment by 2198310932i1** [comment]
Thanks gurkirt! I appreciate it! Funny that the official facebookresearch one and the torchvisions differ. Some make use of a temporal transform, and others don't. 

Just asked the group behind the [https://github.com/kylemin/S3D](Pytorch S3D) repo as well. Basically, what I'd like to do is use their dataset loading + training regimen with transfer learning of their weights.

**Comment by gurkirt** [comment]
Yeah, there is no real standard in this domain.
