### ISSUE TITLE
About dataset of "Spatio-Temporal Action Detection Under Large Motion"

### ISSUE THREAD

**Issue by GibranBenitez** [gurkirt/kinetics-download-prep#7]
This might not be the correct place to post my issue, but I can't do it on the [code you provided.](https://github.com/gurkirt/ActionTrackDetectron)

First of all, thanks for your great work.

I am wondering if you can share or help me to obtain the AVA dataset you used in your recent paper, "Spatio-Temporal Action Detection Under Large Motion."
I want to reproduce the results of Figure 1 of your paper. However, I can't find the complete AVA dataset. I tried from the original [AVA repository](https://research.google.com/ava/download.html), but there are several videos missing from the URLs provided. 

So could you help me with the dataset?

**Comment by gurkirt** [comment]
I did not use AVA in mentioned paper, but you want to download ava use it you use the standard SlowFast process. here is the link https://github.com/facebookresearch/SlowFast/blob/main/slowfast/datasets/DATASET.md#ava
